### ISSUE TITLE
IMO: Chapter13 Jupyter Notebook起動のパラメータについて

### ISSUE THREAD

**Issue by gongqi-zhen** [tomomano/learn-aws-by-coding#33]
動作環境 : mac + Docker Desktop

問題 :  Jupyter Notebookにmacのブラウザから接続出来ない

原因 : Jupyter notebookで外部からの接続を許可してないため

書籍というよりJupyter NotebookやDockerの基礎力類の問題なのですが
以下のオプションにすると読者向けに親切なのかと思いました。

Chapter 13-2: S3道場 の "13-2-2 LEVEL1 : Basic IO" でJupyter Notebookを起動する箇所
```
- (.env) $ jupyter notebook
+ (.env) $ jupyter notebook --allow-root --ip 0.0.0.0
```

これによりportforwardでmacブラウザから接続出来ています。
```
docker run -it -p 8888:8888 -v $HOME/.aws:/root/.aws:ro labc

http://127.0.0.1:8888/?token=xxxxxxxxxxxxxxxxxxxxxxxxx
```

Web版に引き続き書籍で学んでおります。素敵な書籍をありがとうございます。

**Comment by tomomano** [comment]
@gongqi-zhen 

返信遅くなってしまいました．
有益なご指摘どうもありがとうございます．

たしかに， Docker を使ってコンテナ内で Jupyter notebook のサーバーを起動した場合，外 (ホストOS) のブラウザからアクセスするのは，書いていただいたようなオプションの付加が必要ですね．

Stackoverflow に，同様のスレッドが見つかったので後にここを訪れる人のために貼っておきます．
https://stackoverflow.com/questions/38830610/access-jupyter-notebook-running-on-docker-container

**Comment by gongqi-zhen** [comment]
返信ありがとうございます。

![learn-aws-by-coding](https://user-images.githubusercontent.com/26854289/149352683-ebdd964e-ebac-4efd-99d2-875fe7bea194.jpeg)

Stackoverflowのスレッド適切ですね。
