### ISSUE TITLE
13章のハンズオンでdeploy時にエラー

### ISSUE THREAD

**Issue by koiryu** [tomomano/learn-aws-by-coding#44]
ハンズオン実施時にtomomano/labcのdocker imageを利用させていただいています。
13章のハンズオンにて `cdk deploy` を実行するとエラーが表示されます。エラーメッセージは下記のとおりです。

`Deployment failed: Error: Stack Deployments Failed: Error: The stack named Bashoutter failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 84a0cc20-60e4-4ab3-a4ec-6f73977ce9e4)" (RequestToken: 9b204613-8a1b-8bae-cad5-1e50245e6f2a, HandlerErrorCode: InvalidRequest)
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:312:7)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:349:12)`

エラーメッセージを読み、runtimeで指定しているpython3.6はサポートされていないとのことでapp.pyの45行目に記載のruntimeを確認したのですが、PYTHON_3_7なのでなぜ動作しないか不明です。(PYTHON_3_8に変更しても同様のエラーでした。)

ご確認いただけますと幸いです。

**Comment by tomomano** [comment]
@koiryu 
すみません，本件確認する時間が取れず，返信遅くなってしまいました．

たしかにおっしゃるとおりです．
Docker を使ってデプロイをしようとすると同様のエラーが確認できます．

https://github.com/tomomano/learn-aws-by-coding/blob/3b77dc05273e899d9d308fb27884b1f175eaaeba/handson/bashoutter/app.py#L44
となっているのに，変ですね...

Lambda のチュートリアル (https://github.com/tomomano/learn-aws-by-coding/blob/main/handson/serverless/lambda/app.py) は問題なくデプロイできるので，余計不可解です．

もう少し詳しく調べてみますので，少しお時間ください．

**Comment by tomomano** [comment]
原因がわかりました！

https://github.com/tomomano/learn-aws-by-coding/blob/3b77dc05273e899d9d308fb27884b1f175eaaeba/handson/bashoutter/app.py#L36

が原因でした．

この部分で，ウェブページのコンテンツ (HTML, JavaScript) を Bucket に配置しているわけですが，この際にCDKにより自動的に Python のランタイムが作られているようで，それが Python 3.6 を使っているようです．
この部分を削除すればエラーがなくなります．
削除する分，JavaScript などは自分の手でアップロードしなければならなくなります．

このブランチにパッチを施したコードをプッシュしました．
https://github.com/tomomano/learn-aws-by-coding/tree/44-python_runtime_error
関連するコミットは
https://github.com/tomomano/learn-aws-by-coding/commit/e75533e8b7acc3b907f564d0f544f580ea8f956d
です．

koiryu さんの方で確認していただいて，エラーがなくなったことが確認できたらマスターを更新します．

**Comment by tomomano** [comment]
本質的な問題は，このチュートリアルでは CDK version 1 を使っていて，AWS では最近はどんどん version 2 に移行が進んでいることですね．
version 2 への移行は，今後のタスクとしておきます．

**Comment by koiryu** [comment]
@tomomano 
お忙しい中ご対応いただきありがとうございます。修正内容にて動くことを確認しました！
※おっしゃる通りgui/dist配下は手動でアップロードする必要があり、そちらも動作確認済みです。

CDKのバージョンが問題だったのですね。今回は深いところまで理解というよりは、表面的になぞっていたので見当もついていなかったです。。。勉強になりました。

非常にわかりやすい教材であり、公開していただけていること感謝しております。

**Comment by tomomano** [comment]
@koiryu 
ご確認どうもありがとうございます．

https://github.com/tomomano/learn-aws-by-coding/pull/45
にて修正をマスターブランチに組み込みました．

現在では CDK バージョン2を使うことが AWS から推奨されています．
ご自身のプロジェクトで新たに CDK を使う際などは，ぜひ v2 を利用されてください．
